# Generated by Django 4.2.13 on 2024-06-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_account_employee_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(max_length=30),
        ),
    ]
